# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET8.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: list dir
      run: ls -l
      
    - name: Restore dependencies
      run: cd Dotnet8MVCApp && dotnet restore
    
    - name: Build
      run: cd Dotnet8MVCApp && dotnet build --no-restore
      
    - name: Test
      run: cd Dotnet8MVCApp && dotnet test --no-build --verbosity normal
